/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.56
 * Generated at: 2020-08-16 03:16:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.broker;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import board.model.vo.RoomBoard;
import java.util.*;
import member.model.vo.Member;
import broker.model.vo.Broker;

public final class brokerProfile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/views/common/brokerHeader.jsp", Long.valueOf(1595149658000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Member");
    _jspx_imports_classes.add("board.model.vo.RoomBoard");
    _jspx_imports_classes.add("broker.model.vo.Broker");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	//session : 선언없이 사용할 수 있는 jsp내장객체
	Broker brokerLoggedIn = (Broker)session.getAttribute("brokerLoggedIn");
	Member memberLoggedIn = (Member)session.getAttribute("memberLoggedIn");


      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>DamoaBang</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/style.css\" />\r\n");
      out.write("<script src=\"");
      out.print( request.getContextPath() );
      out.write("/js/jquery-3.5.1.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("//로그인\r\n");
      out.write("$(function(){\r\n");
      out.write("\t$(\"#login\").submit(function(){\r\n");
      out.write("\t\tlet $loginId = $(\"#loginId\");\r\n");
      out.write("\t\tlet $loginPwd = $(\"#loginPwd\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif($loginId.val().length == 0) {\r\n");
      out.write("\t\t\talert(\"아이디를 입력하세요.\");\r\n");
      out.write("\t\t\t$loginId.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif($loginPwd.val().length == 0) {\r\n");
      out.write("\t\t\talert(\"비밀번호를 입력하세요.\");\r\n");
      out.write("\t\t\t$loginPwd.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("//중복체크\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t$(\"#userId\").blur(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tlet memberId = $(\"#userId\").val();\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : \"");
      out.print( request.getContextPath() );
      out.write("/member/checkIdDuplicate\",\r\n");
      out.write("\t\t\tmethod: \"GET\", \r\n");
      out.write("\t\t\tdata: {\"memberId\": memberId}, \r\n");
      out.write("\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\tif(data==\"notUsable\"){\r\n");
      out.write("\t\t\t\t\t// 아이디 중복 시 문구\r\n");
      out.write("\t\t\t\t\t$(\"#id_check\").text(\"ID in use\");\r\n");
      out.write("\t\t\t\t\t$(\"#id_check\").css(\"color\", \"red\");\r\n");
      out.write("\t\t\t\t\t$(\"#submit\").attr(\"disabled\", true);\r\n");
      out.write("\t\t\t\t}else if(memberId.length!=0&&data==\"usable\"){\r\n");
      out.write("\t\t\t\t\t$(\"#id_check\").text(\"Available ID\");\r\n");
      out.write("\t\t\t\t\t$(\"#id_check\").css(\"color\", \"blue\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}, error : function() {\r\n");
      out.write("\t\t\t\t\tconsole.log(\"실패\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("//회원 가입\r\n");
      out.write("$(function(){\r\n");
      out.write("\t$(\"#register\").submit(function(){\r\n");
      out.write("\t\t//아이디검사\r\n");
      out.write("\t\tlet $memberId = $(\"#userId\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(!/^[\\w]{4,}$/.test($memberId.val())){\r\n");
      out.write("\t\t\talert(\"아이디가 유효하지 않습니다.\");\r\n");
      out.write("\t\t\t$memberId.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//아이디 중복검사 \r\n");
      out.write("\t\t/* let $isIdValid = $(\"#isIdValid\");\r\n");
      out.write("\t\tif($isIdValid.val() == 0){\r\n");
      out.write("\t\t\talert(\"아이디 중복검사 해주세요.\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t} */\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//비밀번호 검사\r\n");
      out.write("\t\tlet $pwd1 = $(\"#userPwd\");\r\n");
      out.write("\t\tlet $pwd2 = $(\"#userPwdChk\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif($pwd1.val() !== $pwd2.val()){\r\n");
      out.write("\t\t\talert(\"비밀번호가 일치하지 않습니다.\");\r\n");
      out.write("\t\t\t$pwd1.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("//마이페이지 연결 리스트(토글버튼처럼 구현)\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("    \r\n");
      out.write("    $(\".nav-user-link\").click(function(){\r\n");
      out.write("    \t if ( $(\".profile__list\").css(\"display\") == \"none\" )\r\n");
      out.write("    \t\t   $(\".profile__list\").show();\r\n");
      out.write("    \t\t  else\r\n");
      out.write("    \t\t   $(\".profile__list\").hide();\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t$(\".filter-select__type\").click(function(){\r\n");
      out.write("   \t if ( $(\".filter-select__typelist\").css(\"display\") == \"none\" )\r\n");
      out.write("   \t\t   $(\".filter-select__typelist\").show();\r\n");
      out.write("   \t\t  else\r\n");
      out.write("   \t\t   $(\".filter-select__typelist\").hide();\r\n");
      out.write("   });\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t\t<!-- 헤더 -->\r\n");
      out.write("\t\t<header class=\"navbar navbar-expand\" id=\"mainNav\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.write("\" class=\"navbar-brand\">다모아방</a>\r\n");
      out.write("\t\t\t\t<div class=\"navbar-collapse\" id=\"navbarResponsive\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"navbar-nav\">\r\n");
      out.write("\t\t\t\t\t\t");
 if(brokerLoggedIn == null) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item\"><a href=\"");
      out.print(request.getContextPath() );
      out.write("/community/communityQnA\" class=\"nav-link\">커뮤니티</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item\"><a href=\"");
      out.print(request.getContextPath() );
      out.write("/brokerBoard/boardList\" class=\"nav-link\">방 찾기</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item\"><a href=\"#\" class=\"nav-link\" onclick=\"signupbtn()\">중개인로그인</a></li>\r\n");
      out.write("\t\t\t\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item-community\"><a href=\"");
      out.print(request.getContextPath() );
      out.write("/community/communityQnA\" class=\"nav-link\">커뮤니티</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item-room\"><a href=\"");
      out.print(request.getContextPath() );
      out.write("/brokerBoard/boardList\" class=\"nav-link\">방 찾기</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item\"><a href=\"#\" class=\"nav-user-link\"><img style=\"background-color: rgb(0, 255, 0); border-radius: 60%;\" src=\"");
      out.print(request.getContextPath());
      out.write("/images/user.png\" /></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"profile__list\">\r\n");
      out.write("\t\t\t                  <li class=\"login-profile\" id=\"login-profile-img\" ><img style=\"background-color: rgb(0, 255, 0); border-radius: 60%;\" src=\"");
      out.print(request.getContextPath());
      out.write("/images/user.png\" /></li>\r\n");
      out.write("\t\t\t                  <li class=\"login-profile\">");
      out.print( brokerLoggedIn.getBr_name() );
      out.write("</li>\r\n");
      out.write("\t\t\t                  <li class=\"login-profile\" id=\"login-profile-email\">");
      out.print( brokerLoggedIn.getEmail() );
      out.write("</li>\r\n");
      out.write("\t\t\t                  <li class=\"login-mypage\" id=\"login-mypage-info\" ><div onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/broker/brokerProfileView'\">내 정보 보기</div></li>\r\n");
      out.write("\t\t\t                  <li class=\"login-mypage\" id=\"login-mypage-logout\"><div onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/broker/logout'\">로그아웃</div></li> \r\n");
      out.write("\t\t\t              \t</ul>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 로그인 창 -->\r\n");
      out.write("\t\t<div id=\"signWrap\"></div> \r\n");
      out.write("\t        <div id=\"wrap\">\r\n");
      out.write("\t            <div class=\"form-wrap\">\r\n");
      out.write("\t                <div class=\"button-wrap\">\r\n");
      out.write("\t                    <div id=\"btn\"></div>\r\n");
      out.write("\t                    <button type=\"button\" id=\"loginBtn\" class=\"togglebtn\" onclick=\"login()\">로그인</button>\r\n");
      out.write("\t                    <button type=\"button\" id=\"registerBtn\" class=\"togglebtn\" onclick=\"register()\">회원가입</button>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t                <input type=\"button\" class=\"CloseBrokerBtn\" id=\"closeBtn\" value=\"x\" onclick=\"closeBtn();\">\r\n");
      out.write("\t                \r\n");
      out.write("\t                <form action=\"");
      out.print( request.getContextPath() );
      out.write("/broker/login\" id=\"login\" method=\"post\" class=\"input-group\">\r\n");
      out.write("\t\t                <div class=\"social-icons\">\r\n");
      out.write("\t\t                    <img src=\"");
      out.print( request.getContextPath() );
      out.write("/images/naver.png\" alt=\"naver\">\r\n");
      out.write("\t\t                    <img src=\"");
      out.print( request.getContextPath() );
      out.write("/images/facebook.png\" alt=\"facebook\">\r\n");
      out.write("\t\t                    <img src=\"");
      out.print( request.getContextPath() );
      out.write("/images/google.png\" alt=\"google\">\r\n");
      out.write("\t\t                </div> \r\n");
      out.write("\t                    <input type=\"text\" id=\"br_cp_id\" name=\"br_cp_id\" class=\"input-field\" placeholder=\"등록번호를 입력해주세요\" required />\r\n");
      out.write("\t                    <input type=\"password\" id=\"br_loginPwd\" name=\"password\" class=\"input-field\" placeholder=\"비밀번호를 입력해주세요\" required>\r\n");
      out.write("\t                    <div id=\"chkWrap\">\r\n");
      out.write("\t\t                    <div class=\"userChk\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/#'\" >일반회원이세요?</div>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                    <input type=\"submit\" class=\"submit\" value=\"로그인\" />\r\n");
      out.write("\t                    <a id=\"findLink\" href=\"");
      out.print( request.getContextPath() );
      out.write("/member/findMember\">아이디 찾기</a>\r\n");
      out.write("\t                </form>\r\n");
      out.write("\t                <form id=\"register\" action=\"");
      out.print( request.getContextPath() );
      out.write("/member/enroll\" method=\"post\" onsubmit=\"return resisterVal();\" class=\"input-group\">\r\n");
      out.write("\t                    <input type=\"text\" id=\"userId\" name=\"memberId\" class=\"input-field\" placeholder=\"User ID\" required>\r\n");
      out.write("\t                    <div id=\"id_check\"></div>\r\n");
      out.write("\t                    <input type=\"email\" id=\"userEmail\" name=\"email\" class=\"input-field\" placeholder=abc@xyz.com required>\r\n");
      out.write("\t                    <input type=\"password\" id=\"userPwd\" name=\"password\" class=\"input-field\" placeholder=\"Enter Password\" required>\r\n");
      out.write("\t                    <input type=\"password\" id=\"userPwdChk\" class=\"input-field\" placeholder=\"Enter Password Check\" required>\r\n");
      out.write("\t                    <input type=\"tel\" id=\"userPhone\" name=\"phone\" class=\"input-field\" placeholder=\"(-없이)01012345678\" maxlength=\"11\" required>\r\n");
      out.write("\t                    <button class=\"submit\">회원가입</button>\r\n");
      out.write("\t                    <a href=\"");
      out.print( request.getContextPath() );
      out.write("/broker/enroll\">중개인 회원가입</a>\r\n");
      out.write("\t                </form>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t//로그인 관련\r\n");
      out.write("\t\tlet x = document.getElementById(\"login\");\r\n");
      out.write("\t\tlet y = document.getElementById(\"register\");\r\n");
      out.write("\t\tlet z = document.getElementById(\"btn\");\r\n");
      out.write("\t\tlet loginbtn = document.getElementById(\"loginBtn\");\r\n");
      out.write("\t\tlet registerbtn = document.getElementById(\"registerBtn\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction login(){\r\n");
      out.write("\t\t    x.style.left = \"50px\";\r\n");
      out.write("\t\t    y.style.left = \"450px\";\r\n");
      out.write("\t\t    z.style.left = \"0\";\r\n");
      out.write("\t\t    loginbtn.style.color = \"white\";\r\n");
      out.write("\t\t    registerbtn.style.color = \"black\";\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction register(){\r\n");
      out.write("\t\t    x.style.left = \"-400px\";\r\n");
      out.write("\t\t    y.style.left = \"50px\";\r\n");
      out.write("\t\t    z.style.left = \"110px\";\r\n");
      out.write("\t\t    loginbtn.style.color = \"black\";\r\n");
      out.write("\t\t    registerbtn.style.color = \"white\";\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction signupbtn() {\r\n");
      out.write("\t\t    wrap.style.display = \"block\";\r\n");
      out.write("\t\t    signWrap.style.display = \"block\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction closeBtn() {\r\n");
      out.write("\t\t    wrap.style.display = \"none\";\r\n");
      out.write("\t\t    signWrap.style.display = \"none\";\r\n");
      out.write("\t\t    $(\"#register\").children().val('');\r\n");
      out.write("\t\t    $(\"#loginPwd\").val('');\r\n");
      out.write("\t\t    $(\"#id_check\").text(\"\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t</script>");
      out.write('\r');
      out.write('\n');

	List<RoomBoard> list = (List<RoomBoard>)request.getAttribute("list");
	String pageBar = (String)request.getAttribute("pageBar");
	int cnt = (int)request.getAttribute("totalContents");
	Broker broker = (Broker)request.getAttribute("broker");

      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/brokermember.css\" />\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".profile-nav\").click(function(){\r\n");
      out.write("\t\t$(\".sub1\").css(\"display\", \"block\");\r\n");
      out.write("\t\t$(\".mypage-alldiv\").css(\"display\", \"block\");\r\n");
      out.write("\t\t$(\".mypage-Resultdiv\").css(\"display\", \"none\");\r\n");
      out.write("\t\t$(\".mypage-ForSaleManage\").css(\"display\", \"none\");\r\n");
      out.write("\t\t$(\".mypage-profile1_1\").css(\"display\", \"inline-block\");\r\n");
      out.write("\t\t$(\".mypage-profile1\").css(\"display\", \"inline-block\");\r\n");
      out.write("\t\t$(\".mypage-profile2_2\").css(\"display\", \"none\");\r\n");
      out.write("\t\t$(\".mypage-profile2\").css(\"display\", \"none\");\r\n");
      out.write("\t\t$(\".mypage-profile3_3\").css(\"display\", \"none\");\r\n");
      out.write("\t\t$(\".mypage-profile3\").css(\"display\", \"none\");\r\n");
      out.write("\t\t$(\".edit-info1\").css(\"display\", \"none\");\r\n");
      out.write("\t\t$(\".edit-info2\").css(\"display\", \"none\");\r\n");
      out.write("\t\t$(\".profile-nav\").css(\"color\", \"rgb(255, 138, 61)\");\r\n");
      out.write("\t\t$(\".setting-nav\").css(\"color\", \"#000\");\r\n");
      out.write("\t\t$(\".sub2\").css(\"display\", \"none\");\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\".setting-nav\").click(function(){\r\n");
      out.write("\t\t$(\".sub1\").css(\"display\", \"none\");\r\n");
      out.write("\t\t$(\".mypage-alldiv\").css(\"display\", \"none\");\r\n");
      out.write("\t\t$(\".mypage-Resultdiv\").css(\"display\", \"none\");\r\n");
      out.write("\t\t$(\".mypage-ForSaleManage\").css(\"display\", \"none\");\r\n");
      out.write("\t\t$(\".mypage-profile1_1\").css(\"display\", \"none\");\r\n");
      out.write("\t\t$(\".mypage-profile1\").css(\"display\", \"none\");\r\n");
      out.write("\t\t$(\".mypage-profile2_2\").css(\"display\", \"none\");\r\n");
      out.write("\t\t$(\".mypage-profile2\").css(\"display\", \"none\");\r\n");
      out.write("\t\t$(\".mypage-profile3_3\").css(\"display\", \"none\");\r\n");
      out.write("\t\t$(\".mypage-profile3\").css(\"display\", \"none\");\r\n");
      out.write("\t\t$(\".sub2\").css(\"display\", \"block\");\r\n");
      out.write("\t\t$(\".edit-info1\").css(\"display\", \"block\");\r\n");
      out.write("\t\t$(\".edit-info2\").css(\"display\", \"none\");\r\n");
      out.write("\t\t$(\".setting-nav\").css(\"color\", \"rgb(255, 138, 61)\");\r\n");
      out.write("\t\t$(\".profile-nav\").css(\"color\", \"#000\");\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\t$(\".click1\").click(function() {\r\n");
      out.write("\t\t\t$(\".mypage-alldiv\").css(\"display\", \"block\");\r\n");
      out.write("\t\t\t$(\".mypage-Resultdiv\").css(\"display\", \"none\");\r\n");
      out.write("\t\t\t$(\".mypage-ForSaleManage\").css(\"display\", \"none\");\r\n");
      out.write("\t\t\t$(\".mypage-profile1_1\").css(\"display\", \"inline-block\");\r\n");
      out.write("\t\t\t$(\".mypage-profile1\").css(\"display\", \"inline-block\");\r\n");
      out.write("\t\t\t$(\".mypage-profile2_2\").css(\"display\", \"none\");\r\n");
      out.write("\t\t\t$(\".mypage-profile2\").css(\"display\", \"none\");\r\n");
      out.write("\t\t\t$(\".mypage-profile3_3\").css(\"display\", \"none\");\r\n");
      out.write("\t\t\t$(\".mypage-profile3\").css(\"display\", \"none\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\".click2\").click(function() {\r\n");
      out.write("\t\t\t$(\".mypage-alldiv\").css(\"display\", \"none\");\r\n");
      out.write("\t\t\t$(\".mypage-Resultdiv\").css(\"display\", \"block\");\r\n");
      out.write("\t\t\t$(\".mypage-ForSaleManage\").css(\"display\", \"none\");\r\n");
      out.write("\t\t\t$(\".mypage-profile1_1\").css(\"display\", \"none\");\r\n");
      out.write("\t\t\t$(\".mypage-profile1\").css(\"display\", \"none\");\r\n");
      out.write("\t\t\t$(\".mypage-profile2_2\").css(\"display\", \"inline-block\");\r\n");
      out.write("\t\t\t$(\".mypage-profile2\").css(\"display\", \"inline-block\");\r\n");
      out.write("\t\t\t$(\".mypage-profile3_3\").css(\"display\", \"none\");\r\n");
      out.write("\t\t\t$(\".mypage-profile3\").css(\"display\", \"none\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\".click3\").click(function() {\r\n");
      out.write("\t\t\t$(\".mypage-alldiv\").css(\"display\", \"none\");\r\n");
      out.write("\t\t\t$(\".mypage-Resultdiv\").css(\"display\", \"none\");\r\n");
      out.write("\t\t\t$(\".mypage-ForSaleManage\").css(\"display\", \"block\");\r\n");
      out.write("\t\t\t$(\".mypage-profile1_1\").css(\"display\", \"none\");\r\n");
      out.write("\t\t\t$(\".mypage-profile1\").css(\"display\", \"none\");\r\n");
      out.write("\t\t\t$(\".mypage-profile2_2\").css(\"display\", \"none\");\r\n");
      out.write("\t\t\t$(\".mypage-profile2\").css(\"display\", \"none\");\r\n");
      out.write("\t\t\t$(\".mypage-profile3_3\").css(\"display\", \"inline-block\");\r\n");
      out.write("\t\t\t$(\".mypage-profile3\").css(\"display\", \"inline-block\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\".click4\").click(function() {\r\n");
      out.write("\t\t\t$(\".mypage-alldiv\").css(\"display\", \"none\");\r\n");
      out.write("\t\t\t$(\".mypage-Resultdiv\").css(\"display\", \"none\");\r\n");
      out.write("\t\t\t$(\".mypage-ForSaleManage\").css(\"display\", \"none\");\r\n");
      out.write("\t\t\t$(\".edit-info1\").css(\"display\", \"block\");\r\n");
      out.write("\t\t\t$(\".edit-info2\").css(\"display\", \"none\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\".click5\").click(function() {\r\n");
      out.write("\t\t\t$(\".mypage-alldiv\").css(\"display\", \"none\");\r\n");
      out.write("\t\t\t$(\".mypage-Resultdiv\").css(\"display\", \"none\");\r\n");
      out.write("\t\t\t$(\".mypage-ForSaleManage\").css(\"display\", \"none\");\r\n");
      out.write("\t\t\t$(\".edit-info1\").css(\"display\", \"none\");\r\n");
      out.write("\t\t\t$(\".edit-info2\").css(\"display\", \"block\");\r\n");
      out.write("\t\t});\r\n");
      out.write("});\r\n");
      out.write("$(function(){\r\n");
      out.write("\t$(\"#passwordUpdateFrm\").submit(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\tvar $newPwd = $(\"#newPassword\");\r\n");
      out.write("\tvar $newPwdChk = $(\"#newPasswordCheck\");\r\n");
      out.write("\t\r\n");
      out.write("\tif($newPwd.val() != $newPwdChk.val()){\r\n");
      out.write("\t\talert(\"입력한 비밀번호가 일치하지 않습니다.\");\r\n");
      out.write("\t\t$newPwd.select();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\treturn true;\t\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("//탈퇴\r\n");
      out.write("function deleteMember(){\r\n");
      out.write("\tif(!confirm(\"정말 탈퇴하시겠습니까?\")) return;\r\n");
      out.write("\t$(\"[name=deleteMemberFrm]\").submit();\r\n");
      out.write("}\r\n");
      out.write("$(\"#file\").on('change',function(){\r\n");
      out.write("\t  var fileName = $(\"#file\").val();\r\n");
      out.write("\t  $(\".upload-name\").val(fileName);\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\t<div class=\"mypage-nav-bar\">\r\n");
      out.write("\t\t<a class=\"profile-nav\">프로필&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a>\r\n");
      out.write("\t\t<a class=\"setting-nav\">설정</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"sub1\">\r\n");
      out.write("\t\t<a class=\"click1\">모두보기&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a>\r\n");
      out.write("\t\t<a class=\"click2\">실적보기</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t<a class=\"click3\">매물관리</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"sub2\">\r\n");
      out.write("\t\t<a class=\"click4\">회원정보수정</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t<a class=\"click5\">비밀번호 변경</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"mypage-alldiv\">\r\n");
      out.write("\t<div class=\"mypage-profile1_1\">\r\n");
      out.write("\t<div class=\"mypage-profile1\">\r\n");
      out.write("\t\t<section class=\"mypage-allView\">\r\n");
      out.write("\t\t\t<form method=\"post\" action=\"");
      out.print(request.getContextPath() );
      out.write("/broker/brokerProfile\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th></th>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<img id=\"profileImg\" src=\"");
      out.print( request.getContextPath() );
      out.write("/upload/broker/");
      out.print( brokerLoggedIn.getProfile() );
      out.write("\" onerror=\"this.src='");
      out.print( request.getContextPath() );
      out.write("/upload/member/user.png'\" alt=\"profile\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th></th>\r\n");
      out.write("\t\t\t\t\t<td >\t\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name = \"memberId\" class=\"mypage-id\" value=\"");
      out.print(brokerLoggedIn.getBr_name() );
      out.write("\" readonly />\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th></th>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"filebox\"> \r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"file\" >사진 업로드</label> \r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"file\" id=\"file\" name=\"profile\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <input class=\"upload-name\" value=\"파일선택\">  -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th></th>\r\n");
      out.write("\t\t\t\t\t<td>\t\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"프로필 변경\" />\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t</form>\t\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t<div class=\"allview-content\" >\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<p class=\"allview-result\">나의 실적</p>\r\n");
      out.write("\t\t<div class=\"myResultState-div\">\r\n");
      out.write("\t\t<p class=\"myStateResult\">");
      out.print(broker.getSellcount() );
      out.write("회의 거래를 성사시켰습니다! </p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<p class=\"myForSalelistallview\">내가 올린 매물 <span id=\"conLink1\" class=\"click3\">전체보기</span></p>\r\n");
      out.write("\t\t ");
 
		 if(list == null || list.isEmpty()){ 
      out.write("           \r\n");
      out.write("\t\t\t\t<div>올린 매물이 없습니다.</div>\r\n");
      out.write("\t\t");
 
			} 
		   	else {
				for(RoomBoard b : list){
		
      out.write(" \r\n");
      out.write("\t\t<a class=\"noneHover\" href=\"");
      out.print( request.getContextPath() );
      out.write("/brokerBoard/boardView?board_num=");
      out.print( b.getBoard_num() );
      out.write("&br=");
      out.print( b.getBr_cp_id() );
      out.write("\">\r\n");
      out.write("\t\t<section id=\"br_itemInfo\">\r\n");
      out.write("\t\t\t<p class=\"SearchRoomForSaleparagraph\">");
      out.print( b.getBoard_title() );
      out.write("<span class=\"SearchRoomclickLikeEnrollDate\">");
      out.print( b.getEnrolldate() );
      out.write("</span></p>\r\n");
      out.write("\t\t\t<p class=\"approveForSaleRoom\">");
      out.print( b.getOk().equals("T")?"승인":"미승인" );
      out.write("</p>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t");
 		}
		
			} 
		
      out.write(" \r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t<div class=\"allviewPageBar\" id='pageBar'>\r\n");
      out.write("\t\t\t");
      out.print( pageBar );
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"mypage-Resultdiv\">\r\n");
      out.write("\t<div class=\"mypage-profile2_2\">\r\n");
      out.write("\t<div class=\"mypage-profile2\">\r\n");
      out.write("\t\t<section class=\"mypage-allView\">\r\n");
      out.write("\t\t\t<form method=\"post\" action=\"");
      out.print(request.getContextPath() );
      out.write("/broker/brokerProfile\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th></th>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<img id=\"profileImg\" src=\"");
      out.print( request.getContextPath() );
      out.write("/upload/broker/");
      out.print( brokerLoggedIn.getProfile() );
      out.write("\" onerror=\"this.src='");
      out.print( request.getContextPath() );
      out.write("/upload/member/user.png'\" alt=\"profile\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th></th>\r\n");
      out.write("\t\t\t\t\t<td >\t\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name = \"memberId\" class=\"mypage-id\" value=\"");
      out.print(brokerLoggedIn.getBr_name() );
      out.write("\" readonly />\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th></th>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"filebox\"> \r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"file\" >사진 업로드</label> \r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"file\" id=\"file\" name=\"profile\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <input class=\"upload-name\" value=\"파일선택\">  -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th></th>\r\n");
      out.write("\t\t\t\t\t<td>\t\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"프로필 변경\" />\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t</form>\t\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t<div class=\"brokerForSales\">\r\n");
      out.write("\t\t\t<p class=\"memberIdparagraph\"><span class=\"countPercentMemberId\">");
      out.print(brokerLoggedIn.getBr_name() );
      out.write("</span>님은</p>\r\n");
      out.write("\t\t\t<p>누적 <span class=\"countPercentMemberId\">");
      out.print(broker.getSellcount() );
      out.write("회</span>의 거래를 성사시켰습니다!</p> \t\t\r\n");
      out.write("\t\t\t<p>상위 <span class=\"countPercent\" >7%</span>의 베스트 중개인입니다.</p>\r\n");
      out.write("\t\t</div>\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"mypage-ForSaleManage\">\r\n");
      out.write("\t<div class=\"mypage-profile3_3\">\r\n");
      out.write("\t<div class=\"mypage-profile3\">\r\n");
      out.write("\t\t<section class=\"mypage-allView\">\r\n");
      out.write("\t\t\t<form method=\"post\" action=\"");
      out.print(request.getContextPath() );
      out.write("/broker/brokerProfile\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th></th>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<img id=\"profileImg\" src=\"");
      out.print( request.getContextPath() );
      out.write("/upload/broker/");
      out.print( brokerLoggedIn.getProfile() );
      out.write("\" onerror=\"this.src='");
      out.print( request.getContextPath() );
      out.write("/upload/member/user.png'\" alt=\"profile\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th></th>\r\n");
      out.write("\t\t\t\t\t<td >\t\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name = \"memberId\" class=\"mypage-id\" value=\"");
      out.print(brokerLoggedIn.getBr_name() );
      out.write("\" readonly />\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th></th>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"filebox\"> \r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"file\" >사진 업로드</label> \r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"file\" id=\"file\" name=\"profile\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <input class=\"upload-name\" value=\"파일선택\">  -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th></th>\r\n");
      out.write("\t\t\t\t\t<td>\t\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"프로필 변경\" />\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t</form>\t\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t ");
 if(list == null || list.isEmpty()){ 
      out.write("           \r\n");
      out.write("\t<div class=\"myForSaleListViewCount\">\r\n");
      out.write("\t\t<p class=\"myForSaleCountViewtotal\">전체 : ");
      out.print( cnt );
      out.write("개</p>\r\n");
      out.write("\t\t\t\t<div class=\"hasnotClickForSaleboard\">올린 매물이 없습니다.</div>\r\n");
      out.write("\t\t");
 
			} 
		   	else {
				for(RoomBoard b : list){
		
      out.write(" \r\n");
      out.write("\t\t<section id=\"my_ForSaleroomImg\">\r\n");
      out.write("\t\t\t<a href=\"");
      out.print( request.getContextPath() );
      out.write("/brokerBoard/boardView?board_num=");
      out.print( b.getBoard_num() );
      out.write("&br=");
      out.print( b.getBr_cp_id() );
      out.write("\" class=\"image featured\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/upload/board/");
      out.print(b.getRenameName() );
      out.write("\" onerror=\"this.src='");
      out.print( request.getContextPath() );
      out.write("/images/roomImg01.jpg'\" alt=\"\"></a>\r\n");
      out.write("\t\t\t<p class=\"myForSaleRoomImgTitle\">");
      out.print( b.getBoard_title() );
      out.write("</p>\r\n");
      out.write("\t\t\t<p id=\"commuTxtId\">");
      out.print( b.getContent().length()<19 ? b.getContent() : b.getContent().substring(0,20) );
      out.write("</p>\r\n");
      out.write("\t\t\t<p id=\"commuRoomViews\" style=\"text-align: center;\">");
      out.print( b.getOk().equals("T")?"승인":"미승인" );
      out.write("</p>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t");
 		}
		
			} 
		
      out.write(" \r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t<div style=\"clear:both;text-align: center;margin:0 0 50px 210px;\" id='pageBar'>\r\n");
      out.write("\t\t\t");
      out.print( pageBar );
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"edit-info1\">\r\n");
      out.write("\t\t<section class=\"edit-infoPage\">\r\n");
      out.write("\t\t\t<input type=\"button\" id=deleteMem value=\"탈퇴하기\" onclick=\"deleteMember();\">\r\n");
      out.write("\t\t\t<p>회원정보 수정</p>\r\n");
      out.write("\t\t\t<form action=\"");
      out.print(request.getContextPath() );
      out.write("/broker/deletebroker\" name=\"deleteMemberFrm\" method=\"POST\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"memberId\" value=\"\" />\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t<form name=\"memberUpdateFrm\" \r\n");
      out.write("\t\t\t\t  action=\"");
      out.print( request.getContextPath() );
      out.write("/broker/brokerUpdate\" method=\"post\">\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>아이디</th>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"br_cp_id\" id=\"memberId_\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   value=\"");
      out.print( brokerLoggedIn.getBr_cp_id() );
      out.write("\" readonly required>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>이메일</th>\r\n");
      out.write("\t\t\t\t\t\t<td>\t\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"email\"  name=\"email\" id=\"email\"\r\n");
      out.write("\t\t\t\t\t\t\t\t   value=\"");
      out.print( brokerLoggedIn.getEmail() );
      out.write("\"><br>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>전화번호</th>\r\n");
      out.write("\t\t\t\t\t\t<td>\t\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"tel\"  id=\"userPhone\" name=\"phone\"\r\n");
      out.write("\t\t\t\t\t\t\t\t   value=\"");
      out.print( brokerLoggedIn.getPhone() );
      out.write("\"><br>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<div class=\"editBtn\">\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"회원정보수정\" >\r\n");
      out.write("\t\t\t\t\t<input type=\"reset\" value=\"초기화\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"edit-info2\" >\r\n");
      out.write("\t\t<section class=\"edit-passwordPage\">\r\n");
      out.write("\t\t\t<p>비밀번호 변경</p>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<form name=\"passwordUpdateFrm\" id=\"passwordUpdateFrm\" \r\n");
      out.write("\t\t\t\t  action=\"");
      out.print( request.getContextPath() );
      out.write("/broker/updatePassword\" method=\"post\">\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>현재 비밀번호</th>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"password\" name=\"password\" id=\"password\" required>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>변경 비밀번호</th>\r\n");
      out.write("\t\t\t\t\t\t<td>\t\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"password\" name=\"newPassword\" id=\"newPassword\"><br>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>비밀번호 확인</th>\r\n");
      out.write("\t\t\t\t\t\t<td>\t\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"password\" id=\"newPasswordCheck\" required><br>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<div class=\"editBtn\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"br_cp_id\" value=\"");
      out.print( brokerLoggedIn.getBr_cp_id() );
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"비밀번호 변경\"  >\r\n");
      out.write("\t\t\t\t\t<input type=\"reset\" value=\"초기화\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
